"""Canonical Live constants derived from the deployed data model."""

LIVE_DOCTYPE = "AOS Live Stream"
LIVE_VIEW_DOCTYPE = "AOS Live Stream View"
LIVE_MESSAGE_DOCTYPE = "AOS Live Message"
LIVE_COHOST_DOCTYPE = "AOS Live CoHost"
LIVE_REACTION_DOCTYPE = "AOS Live Stream Reaction"
LIVE_WEBHOOK_EVENT_DOCTYPE = "AOS LiveKit Webhook Event"

STATUS_SCHEDULED = "scheduled"
STATUS_LIVE = "live"
STATUS_ENDED = "ended"
ACTIVE_STATUSES = frozenset({STATUS_LIVE})
TERMINAL_STATUSES = frozenset({STATUS_ENDED})

ROLE_HOST = "host"
ROLE_COHOST = "cohost"
ROLE_VIEWER = "viewer"
VALID_ROLES = frozenset({ROLE_HOST, ROLE_COHOST, ROLE_VIEWER})

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 50
MAX_SESSION_ID_LENGTH = 128
MAX_TITLE_LENGTH = 140
MAX_COMMENT_LENGTH = 500
MAX_REASON_LENGTH = 240
MAX_CURSOR_LENGTH = 2048
LIVEKIT_LIVE_TOKEN_TTL_DEFAULT_MINUTES = 15
LIVEKIT_LIVE_TOKEN_TTL_MAX_MINUTES = 30
LIVEKIT_ADMIN_TIMEOUT_SECONDS = 5
LIVEKIT_ADMIN_RETRY_ATTEMPTS = 3
LIVEKIT_RECONCILIATION_BATCH_SIZE = 100
LIVE_STALE_SESSION_SECONDS = 120
LIVE_ORPHAN_GRACE_SECONDS = 300
