"""Wishlist domain constants."""

from __future__ import annotations

WISHLIST_STATUS_ACTIVE = "Active"
WISHLIST_STATUS_REMOVED = "Removed"
WISHLIST_STATUSES = frozenset({WISHLIST_STATUS_ACTIVE, WISHLIST_STATUS_REMOVED})

WISHLIST_LIST_LIMIT_PER_MINUTE_PER_USER = 120
WISHLIST_MUTATION_LIMIT_PER_MINUTE_PER_USER = 60
