"""Canonical Shorts domain limits, states and stable internal labels."""
from __future__ import annotations

FEED_DEFAULT_LIMIT = 10
FEED_MAX_LIMIT = 30
LIST_DEFAULT_LIMIT = 20
LIST_MAX_LIMIT = 50
COMMENTS_DEFAULT_LIMIT = 20
COMMENTS_MAX_LIMIT = 100
COMMENT_MAX_LENGTH = 500
CAPTION_MAX_LENGTH = 1000
MAX_HASHTAGS = 10
MAX_MENTIONS = 20
MAX_PHOTOS = 10
MAX_AD_LINKS = 8
MAX_SHORT_DURATION_SECONDS = 600
MAX_EVENT_BATCH = 40

CONTENT_TYPE_VIDEO = "Video"
CONTENT_TYPE_PHOTO = "Photo"
CONTENT_TYPES = (CONTENT_TYPE_VIDEO, CONTENT_TYPE_PHOTO)

CONTENT_MODES = ("shop", "geo", "vibes", "learn")
AUDIENCES = ("everyone", "followers", "friends", "only_me")

LIFECYCLE_DRAFT = "Draft"
LIFECYCLE_PROCESSING = "Processing"
LIFECYCLE_PENDING_REVIEW = "Pending Review"
LIFECYCLE_PUBLISHED = "Published"
LIFECYCLE_REJECTED = "Rejected"
LIFECYCLE_HIDDEN = "Hidden"
LIFECYCLE_FAILED = "Failed"
LIFECYCLE_DELETED = "Deleted"
LIFECYCLE_STATES = (
    LIFECYCLE_DRAFT,
    LIFECYCLE_PROCESSING,
    LIFECYCLE_PENDING_REVIEW,
    LIFECYCLE_PUBLISHED,
    LIFECYCLE_REJECTED,
    LIFECYCLE_HIDDEN,
    LIFECYCLE_FAILED,
    LIFECYCLE_DELETED,
)

PROCESSING_NOT_REQUIRED = "Not Required"
PROCESSING_QUEUED = "Queued"
PROCESSING_RUNNING = "Processing"
PROCESSING_RETRY_WAITING = "Retry Waiting"
PROCESSING_READY = "Ready"
PROCESSING_FAILED = "Failed"
PROCESSING_CANCELLED = "Cancelled"
PROCESSING_STATES = (
    PROCESSING_NOT_REQUIRED,
    PROCESSING_QUEUED,
    PROCESSING_RUNNING,
    PROCESSING_RETRY_WAITING,
    PROCESSING_READY,
    PROCESSING_FAILED,
    PROCESSING_CANCELLED,
)

MODERATION_DRAFT = "Draft"
MODERATION_PENDING = "Pending"
MODERATION_APPROVED = "Approved"
MODERATION_REJECTED = "Rejected"
MODERATION_HIDDEN = "Hidden"
MODERATION_STATES = (
    MODERATION_DRAFT,
    MODERATION_PENDING,
    MODERATION_APPROVED,
    MODERATION_REJECTED,
    MODERATION_HIDDEN,
)

VIDEO_OPERATION_PROCESS = "Process"
VIDEO_OPERATION_DOWNLOAD = "Download"
VIDEO_OPERATION_SIDE_BY_SIDE = "Side By Side"
VIDEO_OPERATION_SEGMENT = "Segment"
VIDEO_OPERATIONS = (
    VIDEO_OPERATION_PROCESS,
    VIDEO_OPERATION_DOWNLOAD,
    VIDEO_OPERATION_SIDE_BY_SIDE,
    VIDEO_OPERATION_SEGMENT,
)

REUSE_SIDE_BY_SIDE = "Side By Side"
REUSE_SEGMENT = "Segment"

EVENT_TYPES = {
    "impression",
    "playback_start",
    "qualified_view",
    "watch",
    "complete",
    "rewatch",
    "early_skip",
    "share",
    "follow_from_content",
    "download",
}

SOUND_SOURCE_LIBRARY = "library"
SOUND_SOURCE_UPLOADED = "uploaded"
SOUND_SOURCE_ORIGINAL = "original"
# aliases retained inside the service package only; they are not API aliases.
SOUND_SOURCE_TYPE_LIBRARY = SOUND_SOURCE_LIBRARY
SOUND_SOURCE_TYPE_UPLOADED = SOUND_SOURCE_UPLOADED
SOUND_SOURCE_TYPE_ORIGINAL = SOUND_SOURCE_ORIGINAL
SOUND_ACTIVE = "active"
SOUND_STATUS_ACTIVE = SOUND_ACTIVE
