"""
Seller API constants.
"""

from __future__ import annotations


# Seller discovery and profile.
LIST_SELLERS_LIMIT_PER_MINUTE_PER_IP = 900
GET_SELLER_LIMIT_PER_MINUTE_PER_IP = 600
GET_MY_SELLER_STATUS_LIMIT_PER_MINUTE_PER_USER = 120
UPDATE_MY_SELLER_LIMIT_PER_MINUTE_PER_USER = 20


# Seller location APIs.
SET_MY_SELLER_LOCATION_LIMIT_PER_MINUTE_PER_USER = 10
REMOVE_MY_SELLER_LOCATION_LIMIT_PER_MINUTE_PER_USER = 5
GET_MY_SELLER_LOCATION_LIMIT_PER_MINUTE_PER_USER = 120
GET_SELLER_LOCATION_LIMIT_PER_MINUTE_PER_IP = 600
LIST_SELLER_MAP_POINTS_LIMIT_PER_MINUTE_PER_IP = 300


# Seller location validation.
LOCATION_NAME_MAX_LENGTH = 140
LOCATION_INSTRUCTIONS_MAX_LENGTH = 500
DISPLAY_ADDRESS_MAX_LENGTH = 500
LOCALITY_MAX_LENGTH = 140
REGION_MAX_LENGTH = 140

COUNTRY_CODE_LENGTH = 2

LATITUDE_MIN = -90.0
LATITUDE_MAX = 90.0

LONGITUDE_MIN = -180.0
LONGITUDE_MAX = 180.0


# Nearby seller discovery.
NEARBY_SELLERS_DEFAULT_RADIUS_KM = 10.0
NEARBY_SELLERS_MAX_RADIUS_KM = 100.0
NEARBY_SELLERS_MIN_RADIUS_KM = 0.1

# Map viewport seller discovery.
SELLER_MAP_POINTS_DEFAULT_ZOOM = 12
SELLER_MAP_POINTS_MIN_ZOOM = 3
SELLER_MAP_POINTS_MAX_ZOOM = 20
SELLER_MAP_POINTS_MAX_RAW_SELLERS = 5000
SELLER_MAP_POINTS_MAX_ITEMS = 300
