"""
Seller API constants.
"""

from __future__ import annotations


# Seller discovery and profile.
LIST_SELLERS_LIMIT_PER_MINUTE_PER_IP = 900
GET_SELLER_LIMIT_PER_MINUTE_PER_IP = 600
GET_MY_SELLER_STATUS_LIMIT_PER_MINUTE_PER_USER = 120
UPDATE_MY_SELLER_LIMIT_PER_MINUTE_PER_USER = 20


# Seller location APIs.
SET_MY_SELLER_LOCATION_LIMIT_PER_MINUTE_PER_USER = 10
REMOVE_MY_SELLER_LOCATION_LIMIT_PER_MINUTE_PER_USER = 5
GET_MY_SELLER_LOCATION_LIMIT_PER_MINUTE_PER_USER = 120
GET_SELLER_LOCATION_LIMIT_PER_MINUTE_PER_IP = 600


# Seller location validation.
LOCATION_NAME_MAX_LENGTH = 140
LOCATION_INSTRUCTIONS_MAX_LENGTH = 500
DISPLAY_ADDRESS_MAX_LENGTH = 500
LOCALITY_MAX_LENGTH = 140
REGION_MAX_LENGTH = 140

COUNTRY_CODE_LENGTH = 2

LATITUDE_MIN = -90.0
LATITUDE_MAX = 90.0

LONGITUDE_MIN = -180.0
LONGITUDE_MAX = 180.0
