"""Accounts endpoint rate limits."""

GET_PROFILE_LIMIT_PER_MINUTE_PER_USER = 60
GET_PUBLIC_PROFILE_LIMIT_PER_MINUTE_PER_USER = 90
UPDATE_PROFILE_LIMIT_PER_MINUTE_PER_USER = 20
AVATAR_CHANGE_LIMIT_PER_HOUR_PER_USER = 20
GET_PREF_LIMIT_PER_MINUTE_PER_USER = 60
UPDATE_PREF_LIMIT_PER_MINUTE_PER_USER = 20
