"""Stable Accounts domain constants."""

from __future__ import annotations

ACCOUNT_STATUS_ACTIVE = "Active"
ACCOUNT_STATUS_DEACTIVATED = "Deactivated"
ACCOUNT_STATUS_DELETED = "Deleted"
ACCOUNT_STATUS_SUSPENDED = "Suspended"
ACCOUNT_STATUSES = {
    ACCOUNT_STATUS_ACTIVE,
    ACCOUNT_STATUS_DEACTIVATED,
    ACCOUNT_STATUS_DELETED,
    ACCOUNT_STATUS_SUSPENDED,
}

ACCOUNT_RESTORE_WINDOW_DAYS = 30

PURGE_STATUS_PENDING = "Pending"
PURGE_STATUS_PURGING = "Purging"
PURGE_STATUS_COMPLETED = "Completed"
PURGE_STATUSES = {PURGE_STATUS_PENDING, PURGE_STATUS_PURGING, PURGE_STATUS_COMPLETED}

# Permanent cleanup is background-only and deliberately bounded.
ACCOUNT_PURGE_SCAN_LIMIT = 20
ACCOUNT_PURGE_SOCIAL_EDGE_BATCH_SIZE = 10_000
PUBLIC_ACCOUNT_ID_PREFIX = "ACC-"
PUBLIC_ACCOUNT_ID_RANDOM_BYTES = 12
PROFILE_IMAGE_PURPOSE = "profile_image"
PROFILE_DOCTYPE = "AOS Profile"
PROFILE_IMAGE_FIELD = "profile_image_media"

PUBLIC_PROFILE_CACHE_SECONDS = 60
PRIVATE_CACHE_CONTROL = "private, no-store, max-age=0"
PUBLIC_CACHE_CONTROL = f"public, max-age={PUBLIC_PROFILE_CACHE_SECONDS}"
