"""Maps API constants for the global provider-neutral Maps domain."""

from __future__ import annotations

# RATE LIMITS
AUTOCOMPLETE_PLACES_LIMIT_PER_MINUTE_PER_IP = 180
SEARCH_PLACES_LIMIT_PER_MINUTE_PER_IP = 90
REVERSE_GEOCODE_LIMIT_PER_MINUTE_PER_IP = 120
GET_ROUTE_LIMIT_PER_MINUTE_PER_USER = 60
REFRESH_ROUTE_LIMIT_PER_MINUTE_PER_USER = 30
GET_ROUTE_LIMIT_PER_MINUTE_PER_IP = 240
REFRESH_ROUTE_LIMIT_PER_MINUTE_PER_IP = 120

# INTERNAL SERVICE URLS
DEFAULT_NOMINATIM_BASE_URL = "http://127.0.0.1:8081"
DEFAULT_PHOTON_BASE_URL = "http://127.0.0.1:2322"
DEFAULT_VALHALLA_BASE_URL = "http://127.0.0.1:8002"

# TIMEOUTS
MAP_SERVICE_CONNECT_TIMEOUT_SECONDS = 2
PHOTON_REQUEST_TIMEOUT_SECONDS = 6
NOMINATIM_REQUEST_TIMEOUT_SECONDS = 12
VALHALLA_REQUEST_TIMEOUT_SECONDS = 15

# SEARCH / AUTOCOMPLETE
AUTOCOMPLETE_DEFAULT_LIMIT = 5
AUTOCOMPLETE_MAX_LIMIT = 8
SEARCH_DEFAULT_LIMIT = 10
SEARCH_MAX_LIMIT = 20
SEARCH_MIN_QUERY_LENGTH = 2
SEARCH_MAX_QUERY_LENGTH = 160
SEARCH_ADDRESS_DETAILS = True

GEOCODER_PRIMARY_PHOTON = "photon"
GEOCODER_PRIMARY_NOMINATIM = "nominatim"
GEOCODER_PRIMARY_ALLOWED = {
	GEOCODER_PRIMARY_PHOTON,
	GEOCODER_PRIMARY_NOMINATIM,
}

# REVERSE GEOCODING
REVERSE_GEOCODE_DEFAULT_ZOOM = 18
REVERSE_GEOCODE_ADDRESS_DETAILS = True

# COORDINATES / WGS84
LATITUDE_MIN = -90.0
LATITUDE_MAX = 90.0
LONGITUDE_MIN = -180.0
LONGITUDE_MAX = 180.0
COORDINATE_PRECISION = 7
WORLD_BBOX_WEST = -180.0
WORLD_BBOX_SOUTH = -90.0
WORLD_BBOX_EAST = 180.0
WORLD_BBOX_NORTH = 90.0

# ROUTING
ROUTE_DEFAULT_COSTING = "auto"
ROUTE_ALLOWED_COSTINGS = {"auto", "bicycle", "pedestrian"}
ROUTE_DEFAULT_UNITS = "kilometers"
ROUTE_ALLOWED_UNITS = {"kilometers", "miles"}
ROUTE_DEFAULT_LANGUAGE = "en-US"
ROUTE_MAX_LOCATIONS = 10
ROUTE_SHAPE_FORMAT = "polyline6"

# CACHE
AUTOCOMPLETE_CACHE_TTL_SECONDS = 60
SEARCH_CACHE_TTL_SECONDS = 180
REVERSE_GEOCODE_CACHE_TTL_SECONDS = 3600
ROUTE_CACHE_TTL_SECONDS = 120

# RESPONSE / PAYLOAD LIMITS
PLACE_NAME_MAX_LENGTH = 300
DISPLAY_ADDRESS_MAX_LENGTH = 1000
LOCALITY_MAX_LENGTH = 200
REGION_MAX_LENGTH = 200
POSTCODE_MAX_LENGTH = 40
COUNTRY_NAME_MAX_LENGTH = 120
COUNTRY_CODE_LENGTH = 2
ROUTE_LANGUAGE_MAX_LENGTH = 20

# CONFIGURATION KEYS
NOMINATIM_BASE_URL_CONFIG_KEY = "nominatim_base_url"
PHOTON_BASE_URL_CONFIG_KEY = "photon_base_url"
VALHALLA_BASE_URL_CONFIG_KEY = "valhalla_base_url"
