"""
Constants for Shorts API.

All limits, thresholds, and tunable parameters live here.
Avoid hardcoding values anywhere else.
"""

# FEED

# Pagination
FEED_DEFAULT_LIMIT = 10
FEED_MAX_LIMIT = 50

# Ranking weights (for feed scoring)
RANKING_WEIGHT_VIEWS = 1.0
RANKING_WEIGHT_LIKES = 2.0
RANKING_WEIGHT_COMMENTS = 2.5
RANKING_WEIGHT_SHARES = 3.0
RANKING_WEIGHT_RECENCY = 1.5
RANKING_WEIGHT_COMPLETION = 2.0

# Recency decay (hours)
RECENCY_HALF_LIFE_HOURS = 24


# TRACKING (VIEWS / IMPRESSIONS)

# Minimum watch time to qualify as a view (ms)
MIN_VIEW_MS = 2000  # 2 seconds

# Minimum percentage watched (fallback rule)
MIN_VIEW_PERCENT = 0.3  # 30%

# Throttling
IMPRESSION_THROTTLE_SECONDS = 2
VIEW_UPDATE_THROTTLE_MS = 500


# COMMENTS
COMMENT_MAX_LENGTH = 500
COMMENT_DEFAULT_LIMIT = 20
COMMENT_MAX_LIMIT = 100

REPLY_MAX_LENGTH = 500
REPLY_DEFAULT_LIMIT = 20
REPLY_MAX_LIMIT = 100

# Optional depth control (future-proof)
MAX_COMMENT_DEPTH = 3


# LIKES / SAVES / REPOSTS / DOWNLOADS / SHARES
LIKE_TOGGLE_RATE_LIMIT_PER_MINUTE = 60
SAVE_TOGGLE_RATE_LIMIT_PER_MINUTE = 60
REPOST_TOGGLE_RATE_LIMIT_PER_MINUTE = 60
DOWNLOAD_SHORT_LIMIT_PER_MINUTE_PER_IP = 120
SHARE_SHORT_TO_CHAT_LIMIT_PER_MINUTE = 60
CREATE_SHORT_SHARE_LINK_LIMIT_PER_MINUTE_PER_IP = 300


# SHORTS (CONTENT RULES)

# Content modes
SHORT_CONTENT_MODE_SHOP = "shop"
SHORT_CONTENT_MODE_GEO = "geo"
SHORT_CONTENT_MODE_VIBES = "vibes"
SHORT_CONTENT_MODE_LEARN = "learn"

# Default mode should not require seller/ad.
# Shop shorts are commerce shorts and require seller + active ad.
DEFAULT_SHORT_CONTENT_MODE = SHORT_CONTENT_MODE_GEO

VALID_SHORT_CONTENT_MODES = {
    SHORT_CONTENT_MODE_SHOP,
    SHORT_CONTENT_MODE_GEO,
    SHORT_CONTENT_MODE_VIBES,
    SHORT_CONTENT_MODE_LEARN,
}

# Modes requiring seller/shop context
SHORT_CONTENT_MODES_REQUIRING_SELLER = {
    SHORT_CONTENT_MODE_SHOP,
}

# Modes requiring ad attachment
SHORT_CONTENT_MODES_REQUIRING_AD = {
    SHORT_CONTENT_MODE_SHOP,
}

# Audience visibility
SHORT_AUDIENCE_EVERYONE = "everyone"
SHORT_AUDIENCE_FOLLOWERS = "followers"
SHORT_AUDIENCE_FRIENDS = "friends"
SHORT_AUDIENCE_ONLY_ME = "only_me"

# Default audience keeps existing behavior backward-compatible.
DEFAULT_SHORT_AUDIENCE = SHORT_AUDIENCE_EVERYONE

VALID_SHORT_AUDIENCES = {
    SHORT_AUDIENCE_EVERYONE,
    SHORT_AUDIENCE_FOLLOWERS,
    SHORT_AUDIENCE_FRIENDS,
    SHORT_AUDIENCE_ONLY_ME,
}

# Comment permissions
DEFAULT_ALLOW_COMMENTS = 1

# Download permissions
# Default to off so old/private content does not suddenly become downloadable.
DEFAULT_ALLOW_DOWNLOADS = 0

# Duration limits (seconds)
MAX_SHORT_DURATION_SECONDS = 600

# Caption
CAPTION_MAX_LENGTH = 1000

# Hashtags
MAX_HASHTAGS = 10


# UPLOAD / PROCESSING

# Allowed video types
ALLOWED_VIDEO_EXTENSIONS = {"mp4", "mov", "m4v", "webm"}

# Max upload size (bytes) – optional enforcement
MAX_VIDEO_FILE_SIZE_BYTES = 200 * 1024 * 1024  # 200MB

# Processing timeout (seconds)
VIDEO_PROCESSING_TIMEOUT = 1800  # 30 minutes


# MANAGEMENT / LIBRARY LISTS
MY_SHORTS_DEFAULT_LIMIT = 20
MY_SHORTS_MAX_LIMIT = 50
SAVED_SHORTS_DEFAULT_LIMIT = 20
SAVED_SHORTS_MAX_LIMIT = 50
LIKED_SHORTS_DEFAULT_LIMIT = 20
LIKED_SHORTS_MAX_LIMIT = 50
REPOSTED_SHORTS_DEFAULT_LIMIT = 20
REPOSTED_SHORTS_MAX_LIMIT = 50
USER_SHORTS_DEFAULT_LIMIT = 20
USER_SHORTS_MAX_LIMIT = 50


# RATE LIMITS (API LEVEL)

INIT_UPLOAD_LIMIT_PER_MINUTE_PER_USER = 30
CONFIRM_UPLOAD_LIMIT_PER_MINUTE_PER_USER = 30

FEED_LIMIT_PER_MINUTE_PER_IP = 120

TRACK_VIEW_LIMIT_PER_MINUTE_PER_IP = 600
TRACK_IMPRESSION_LIMIT_PER_MINUTE_PER_IP = 600
TRACK_SHARE_LIMIT_PER_MINUTE_PER_IP = 300

COMMENT_LIMIT_PER_MINUTE_PER_USER = 60


# ANALYTICS

# Batch size for aggregation
ANALYTICS_BATCH_SIZE = 1000

# Default aggregation window (days)
ANALYTICS_DEFAULT_WINDOW_DAYS = 1

# Dashboard query defaults
SHORT_ANALYTICS_LIMIT_PER_MINUTE_PER_USER = 120
GENERAL_SHORT_ANALYTICS_LIMIT_PER_MINUTE_PER_USER = 60
ANALYTICS_DEFAULT_RANGE_DAYS = 30
ANALYTICS_MAX_RANGE_DAYS = 365
ANALYTICS_TOP_DEFAULT_LIMIT = 10
ANALYTICS_TOP_MAX_LIMIT = 50
