# Rate limit defaults (per hour)
REGISTER_LIMIT_PER_HOUR_PER_IP = 10
RESEND_LIMIT_PER_HOUR_PER_EMAIL = 10
VERIFY_LIMIT_PER_HOUR_PER_EMAIL = 30
LOGIN_LIMIT_PER_HOUR_PER_IP = 30
LOGIN_LIMIT_PER_HOUR_PER_EMAIL = 20
FORGOT_REQUEST_LIMIT_PER_HOUR_PER_EMAIL = 10
FORGOT_VERIFY_LIMIT_PER_HOUR_PER_EMAIL = 30
FORGOT_RESET_LIMIT_PER_HOUR_PER_EMAIL = 20
