# Rate limit defaults (per hour)
REGISTER_LIMIT_PER_HOUR_PER_IP = 10
RESEND_LIMIT_PER_HOUR_PER_EMAIL = 10
VERIFY_LIMIT_PER_HOUR_PER_EMAIL = 30
LOGIN_LIMIT_PER_HOUR_PER_IP = 30
LOGIN_LIMIT_PER_HOUR_PER_EMAIL = 20
FORGOT_REQUEST_LIMIT_PER_HOUR_PER_EMAIL = 10
FORGOT_VERIFY_LIMIT_PER_HOUR_PER_EMAIL = 30
FORGOT_RESET_LIMIT_PER_HOUR_PER_EMAIL = 20
CHANGE_PASSWORD_LIMIT_PER_HOUR_PER_USER = 20
CHANGE_PASSWORD_LIMIT_PER_HOUR_PER_IP = 30
GOOGLE_LOGIN_LIMIT_PER_HOUR_PER_IP = 60
APPLE_LOGIN_LIMIT_PER_HOUR_PER_IP = 50

# Delete / restore account
DELETE_ACCOUNT_LIMIT_PER_HOUR_PER_USER = 3
DELETE_ACCOUNT_LIMIT_PER_HOUR_PER_IP = 10
RESTORE_REQUEST_LIMIT_PER_HOUR_PER_EMAIL = 10
RESTORE_REQUEST_LIMIT_PER_HOUR_PER_IP = 20
RESTORE_VERIFY_LIMIT_PER_HOUR_PER_EMAIL = 30
RESTORE_VERIFY_LIMIT_PER_HOUR_PER_IP = 60
ACCOUNT_RESTORE_WINDOW_DAYS = 30
