"""Activity Center API constants."""

LIST_ACTIVITY_LIMIT_PER_MINUTE_PER_USER = 120
HIDE_ACTIVITY_LIMIT_PER_MINUTE_PER_USER = 60
CLEAR_ACTIVITY_LIMIT_PER_MINUTE_PER_USER = 20

DEFAULT_ACTIVITY_LIMIT = 20
MAX_ACTIVITY_LIMIT = 50

ACTIVITY_GROUP_MAX_LEN = 40
ACTIVITY_TYPE_MAX_LEN = 80
