"""
Rate limit constants for Chat endpoints.
All limits are per minute unless stated otherwise.
"""

# Conversation
OPEN_CONVERSATION_LIMIT_PER_MINUTE_PER_USER = 60
LIST_CONVERSATIONS_LIMIT_PER_MINUTE_PER_USER = 120
DELETE_CONVERSATION_LIMIT_PER_MINUTE_PER_USER = 60

# Message
SEND_MESSAGE_LIMIT_PER_MINUTE_PER_USER = 120
LIST_MESSAGES_LIMIT_PER_MINUTE_PER_USER = 300

# Status (High-frequency, must be efficient)
MARK_DELIVERED_LIMIT_PER_MINUTE_PER_USER = 600
MARK_READ_LIMIT_PER_MINUTE_PER_USER = 600

# Realtime / Presence
SEND_TYPING_LIMIT_PER_MINUTE_PER_USER = 600
PRESENCE_BROADCAST_THROTTLE_SECONDS = 10
ONLINE_THRESHOLD_SECONDS = 60
