"""Compatibility exports for Report API constants."""

from aos.services.reports.constants import (  # noqa: F401
    REPORT_AD_LIMIT_PER_MINUTE_PER_USER,
    REPORT_REASONS_LIMIT_PER_MINUTE_PER_USER,
    REPORT_SHORT_LIMIT_PER_MINUTE_PER_USER,
    REPORT_USER_LIMIT_PER_MINUTE_PER_USER,
)

USER_REPORT_DETAILS_MAX_LEN = 1000
SHORT_REPORT_DETAILS_MAX_LEN = 1000
