SAVE_SEARCH_LIMIT_PER_MINUTE_PER_USER = 60
LIST_SEARCH_LIMIT_PER_MINUTE_PER_USER = 60
MAX_SAVED_SEARCHES_PER_USER = 100
LIST_SAVED_SEARCHES_DEFAULT_LIMIT = 100
LIST_SAVED_SEARCHES_MAX_LIMIT = 100
MAX_SAVED_SEARCH_TITLE_LENGTH = 140
MAX_SAVED_SEARCH_PARAMS_BYTES = 16 * 1024
