"""Canonical Notifications API pagination and rate-limit constants."""

# Pagination
NOTIFICATION_DEFAULT_LIMIT = 20
NOTIFICATION_MAX_LIMIT = 50

# Rate limits
GET_PUSH_CONFIG_LIMIT_PER_MINUTE_PER_USER = 30
REGISTER_PUSH_TOKEN_LIMIT_PER_MINUTE_PER_USER = 30
DEACTIVATE_PUSH_TOKEN_LIMIT_PER_MINUTE_PER_USER = 30
LIST_NOTIFICATIONS_LIMIT_PER_MINUTE_PER_USER = 60
MARK_NOTIFICATION_READ_LIMIT_PER_MINUTE_PER_USER = 60
MARK_ALL_NOTIFICATIONS_READ_LIMIT_PER_MINUTE_PER_USER = 30
DELETE_NOTIFICATION_LIMIT_PER_MINUTE_PER_USER = 60
CLEAR_NOTIFICATIONS_LIMIT_PER_MINUTE_PER_USER = 10
