"""Notification API constants and stable category aliases."""

from aos.services.notifications.contracts import (
    CATEGORY_ACCOUNT,
    CATEGORY_ACTIVITY,
    CATEGORY_ALL,
    CATEGORY_COMMUNICATION,
    CATEGORY_MARKETPLACE,
    CATEGORY_TYPES,
    VALID_CATEGORIES,
)

# Stable public aliases retained for existing imports/mobile clients.
NOTIFICATION_CATEGORY_ALL = CATEGORY_ALL
NOTIFICATION_CATEGORY_COMMUNICATION = CATEGORY_COMMUNICATION
NOTIFICATION_CATEGORY_ACTIVITY = CATEGORY_ACTIVITY
NOTIFICATION_CATEGORY_MARKETPLACE = CATEGORY_MARKETPLACE
NOTIFICATION_CATEGORY_ACCOUNT = CATEGORY_ACCOUNT
NOTIFICATION_CATEGORY_TYPES = CATEGORY_TYPES
VALID_NOTIFICATION_CATEGORIES = VALID_CATEGORIES

# Pagination
NOTIFICATION_DEFAULT_LIMIT = 20
NOTIFICATION_MAX_LIMIT = 50

# Rate limits
REGISTER_PUSH_TOKEN_LIMIT_PER_MINUTE_PER_USER = 30
DEACTIVATE_PUSH_TOKEN_LIMIT_PER_MINUTE_PER_USER = 30
LIST_NOTIFICATIONS_LIMIT_PER_MINUTE_PER_USER = 60
MARK_NOTIFICATION_READ_LIMIT_PER_MINUTE_PER_USER = 60
MARK_ALL_NOTIFICATIONS_READ_LIMIT_PER_MINUTE_PER_USER = 30
DELETE_NOTIFICATION_LIMIT_PER_MINUTE_PER_USER = 60
CLEAR_NOTIFICATIONS_LIMIT_PER_MINUTE_PER_USER = 10
