"""
Social API constants.
"""

# Follow actions
TOGGLE_FOLLOW_LIMIT_PER_MINUTE_PER_USER = 30

# Relationship status
GET_RELATIONSHIP_STATUS_LIMIT_PER_MINUTE_PER_USER = 300

# Follow lists
GET_FOLLOWING_LIMIT_PER_MINUTE_PER_USER = 120
GET_FOLLOWERS_LIMIT_PER_MINUTE_PER_USER = 120
GET_FRIENDS_LIMIT_PER_MINUTE_PER_USER = 120

# Social list search
SOCIAL_LIST_SEARCH_MIN_LEN = 2
SOCIAL_LIST_SEARCH_MAX_LEN = 80

# Pagination
DEFAULT_SOCIAL_LIST_LIMIT = 20
MAX_SOCIAL_LIST_LIMIT = 50

# Global user search
SEARCH_USERS_LIMIT_PER_MINUTE_PER_USER = 60
USER_SEARCH_MIN_LEN = 2
USER_SEARCH_MAX_LEN = 80
DEFAULT_USER_SEARCH_LIMIT = 20
MAX_USER_SEARCH_LIMIT = 50
