"""Social endpoint rate and validation constants."""

from aos.services.social.constants import (
    BLOCK_REASON_MAX_LENGTH,
    DEFAULT_LIST_LIMIT,
    DEFAULT_SEARCH_LIMIT,
    MAX_LIST_LIMIT,
    MAX_SEARCH_LIMIT,
    RATE_LIMITS,
    SEARCH_MAX_LENGTH,
    SEARCH_MIN_LENGTH,
)

FOLLOW_LIMIT_PER_MINUTE_PER_USER = RATE_LIMITS["follow"]
UNFOLLOW_LIMIT_PER_MINUTE_PER_USER = RATE_LIMITS["unfollow"]
GET_RELATIONSHIP_STATUS_LIMIT_PER_MINUTE_PER_USER = RATE_LIMITS["relationship"]
GET_FOLLOWING_LIMIT_PER_MINUTE_PER_USER = RATE_LIMITS["following"]
GET_FOLLOWERS_LIMIT_PER_MINUTE_PER_USER = RATE_LIMITS["followers"]
GET_FRIENDS_LIMIT_PER_MINUTE_PER_USER = RATE_LIMITS["friends"]
SOCIAL_LIST_SEARCH_MIN_LEN = SEARCH_MIN_LENGTH
SOCIAL_LIST_SEARCH_MAX_LEN = SEARCH_MAX_LENGTH
DEFAULT_SOCIAL_LIST_LIMIT = DEFAULT_LIST_LIMIT
MAX_SOCIAL_LIST_LIMIT = MAX_LIST_LIMIT
SEARCH_USERS_LIMIT_PER_MINUTE_PER_USER = RATE_LIMITS["search"]
USER_SEARCH_MIN_LEN = SEARCH_MIN_LENGTH
USER_SEARCH_MAX_LEN = SEARCH_MAX_LENGTH
DEFAULT_USER_SEARCH_LIMIT = DEFAULT_SEARCH_LIMIT
MAX_USER_SEARCH_LIMIT = MAX_SEARCH_LIMIT
BLOCK_USER_LIMIT_PER_MINUTE_PER_USER = RATE_LIMITS["block"]
UNBLOCK_USER_LIMIT_PER_MINUTE_PER_USER = RATE_LIMITS["unblock"]
GET_BLOCK_STATUS_LIMIT_PER_MINUTE_PER_USER = RATE_LIMITS["block_status"]
LIST_BLOCKED_USERS_LIMIT_PER_MINUTE_PER_USER = RATE_LIMITS["blocked_list"]
BLOCK_REASON_MAX_LEN = BLOCK_REASON_MAX_LENGTH
DEFAULT_BLOCKED_USERS_LIMIT = DEFAULT_LIST_LIMIT
MAX_BLOCKED_USERS_LIMIT = MAX_LIST_LIMIT
