"""Rate limit constants for Ads endpoints."""

CREATE_AD_LIMIT_PER_MINUTE_PER_USER = 20
LIST_ADS_LIMIT_PER_MINUTE_PER_IP = 600
GET_AD_LIMIT_PER_HOUR_PER_IP = 1200
MY_ADS_LIMIT_PER_MINUTE_PER_USER = 60
UPDATE_AD_LIMIT_PER_MINUTE_PER_USER = 60
SAVE_AD_DRAFT_LIMIT_PER_MINUTE_PER_USER = 120
GET_AD_DRAFT_LIMIT_PER_MINUTE_PER_USER = 120
LIST_AD_DRAFTS_LIMIT_PER_MINUTE_PER_USER = 60
ABANDON_AD_DRAFT_LIMIT_PER_MINUTE_PER_USER = 60
SUBMIT_AD_DRAFT_LIMIT_PER_MINUTE_PER_USER = 20
SET_AD_STATUS_LIMIT_PER_MINUTE_PER_USER = 60
