"""Shared internal LiveKit infrastructure limits."""

ADMIN_RETRY_ATTEMPTS = 3
ADMIN_TIMEOUT_SECONDS = 5
MAX_ADMIN_ROOM_NAME_LENGTH = 128
MAX_ADMIN_PARTICIPANTS = 2_000
MAX_PARTICIPANT_IDENTITY_LENGTH = 128
MAX_TOKEN_METADATA_BYTES = 4_096
