#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${AOS_BACKUP_ENV_FILE:-/etc/aos/backup.env}"

[[ -f "$ENV_FILE" ]] || { echo "Missing backup configuration: $ENV_FILE" >&2; exit 1; }
# shellcheck disable=SC1090
source "$ENV_FILE"

: "${AOS_REPO_ROOT:?AOS_REPO_ROOT is required}"
: "${FRAPPE_BENCH_ROOT:?FRAPPE_BENCH_ROOT is required}"
: "${FRAPPE_SITE:?FRAPPE_SITE is required}"
: "${BACKUP_ROOT:?BACKUP_ROOT is required}"

BACKUP_RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-14}"
DOCKER_COMPOSE_COMMAND="${DOCKER_COMPOSE_COMMAND:-docker compose}"
QUIESCE_DOCKER_VOLUMES="${QUIESCE_DOCKER_VOLUMES:-true}"
INCLUDE_MINIO_DATA="${INCLUDE_MINIO_DATA:-true}"
INCLUDE_QDRANT_DATA="${INCLUDE_QDRANT_DATA:-true}"
INCLUDE_NOMINATIM_DATA="${INCLUDE_NOMINATIM_DATA:-false}"
INCLUDE_MAP_ARTIFACTS="${INCLUDE_MAP_ARTIFACTS:-true}"
INCLUDE_CONFIGURATION="${INCLUDE_CONFIGURATION:-true}"
REMOTE_COPY_COMMAND="${REMOTE_COPY_COMMAND:-}"

TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP_DIR="${BACKUP_ROOT}/${TIMESTAMP}"
WORK_DIR="${BACKUP_DIR}/.work"
STOPPED_SERVICES=()

log() { printf '[%s] %s\n' "$(date -u +%FT%TZ)" "$*"; }
is_true() { [[ "${1,,}" == "true" || "$1" == "1" || "${1,,}" == "yes" ]]; }
require_cmd() { command -v "$1" >/dev/null 2>&1 || { echo "Missing command: $1" >&2; exit 1; }; }

compose() {
  (cd "$AOS_REPO_ROOT" && bash -lc "$DOCKER_COMPOSE_COMMAND $*")
}

cleanup() {
  local exit_code=$?
  if ((${#STOPPED_SERVICES[@]})); then
    log "Restarting quiesced services: ${STOPPED_SERVICES[*]}"
    compose start "${STOPPED_SERVICES[*]}" >/dev/null 2>&1 || true
  fi
  rm -rf "$WORK_DIR"
  if ((exit_code != 0)); then
    log "Backup failed; removing incomplete directory $BACKUP_DIR"
    rm -rf "$BACKUP_DIR"
  fi
  exit "$exit_code"
}
trap cleanup EXIT INT TERM

require_cmd bench
require_cmd docker
require_cmd tar
require_cmd sha256sum
require_cmd find
require_cmd rsync

mkdir -p "$BACKUP_DIR" "$WORK_DIR" "$BACKUP_DIR/frappe" "$BACKUP_DIR/docker" "$BACKUP_DIR/config" "$BACKUP_DIR/maps"

log "Creating native Frappe backup for $FRAPPE_SITE"
(
  cd "$FRAPPE_BENCH_ROOT"
  bench --site "$FRAPPE_SITE" backup --with-files --compress
)

SITE_BACKUP_DIR="${FRAPPE_BENCH_ROOT}/sites/${FRAPPE_SITE}/private/backups"
[[ -d "$SITE_BACKUP_DIR" ]] || { echo "Frappe backup directory not found: $SITE_BACKUP_DIR" >&2; exit 1; }

# Copy files created or modified in the last 15 minutes. This captures the
# database, site config, private files and public files generated by bench.
find "$SITE_BACKUP_DIR" -maxdepth 1 -type f -mmin -15 -print0 |
  xargs -0 -r -I{} cp -a "{}" "$BACKUP_DIR/frappe/"

compgen -G "$BACKUP_DIR/frappe/*" >/dev/null || {
  echo "No fresh Frappe backup files were found." >&2
  exit 1
}

archive_volume() {
  local volume="$1"
  local output="$2"
  log "Archiving Docker volume $volume"
  docker volume inspect "$volume" >/dev/null
  docker run --rm \
    --read-only \
    --security-opt no-new-privileges:true \
    -v "${volume}:/source:ro" \
    -v "${BACKUP_DIR}/docker:/backup:rw" \
    alpine:3.21 \
    sh -c "cd /source && tar -czf /backup/${output} ."
}

if is_true "$QUIESCE_DOCKER_VOLUMES"; then
  services=()
  is_true "$INCLUDE_QDRANT_DATA" && services+=(qdrant)
  is_true "$INCLUDE_MINIO_DATA" && services+=(minio)
  is_true "$INCLUDE_NOMINATIM_DATA" && services+=(nominatim)
  if ((${#services[@]})); then
    log "Quiescing Docker services: ${services[*]}"
    compose stop "${services[*]}"
    STOPPED_SERVICES=("${services[@]}")
  fi
fi

is_true "$INCLUDE_QDRANT_DATA" && archive_volume aos_qdrant_data qdrant_data.tar.gz
is_true "$INCLUDE_MINIO_DATA" && archive_volume aos_minio_data minio_data.tar.gz
is_true "$INCLUDE_NOMINATIM_DATA" && archive_volume aos_nominatim_data nominatim_data.tar.gz

if is_true "$INCLUDE_MAP_ARTIFACTS"; then
  log "Archiving generated map artifacts"
  for path in maps/tiles maps/valhalla maps/kenya; do
    if [[ -e "$AOS_REPO_ROOT/$path" ]]; then
      tar -C "$AOS_REPO_ROOT" -czf "$BACKUP_DIR/maps/$(basename "$path").tar.gz" "$path"
    fi
  done
  [[ -f "$AOS_REPO_ROOT/infra/maps/manifest.env" ]] && cp -a "$AOS_REPO_ROOT/infra/maps/manifest.env" "$BACKUP_DIR/maps/"
fi

if is_true "$INCLUDE_CONFIGURATION"; then
  log "Copying production configuration"
  [[ -f "$AOS_REPO_ROOT/.env" ]] && cp -a "$AOS_REPO_ROOT/.env" "$BACKUP_DIR/config/aos.env"
  [[ -f "$ENV_FILE" ]] && cp -a "$ENV_FILE" "$BACKUP_DIR/config/backup.env"
  [[ -f "$FRAPPE_BENCH_ROOT/sites/common_site_config.json" ]] && cp -a "$FRAPPE_BENCH_ROOT/sites/common_site_config.json" "$BACKUP_DIR/config/"
  [[ -f "$FRAPPE_BENCH_ROOT/sites/$FRAPPE_SITE/site_config.json" ]] && cp -a "$FRAPPE_BENCH_ROOT/sites/$FRAPPE_SITE/site_config.json" "$BACKUP_DIR/config/"
  rsync -a "$AOS_REPO_ROOT/infra/nginx/" "$BACKUP_DIR/config/nginx/" 2>/dev/null || true
  rsync -a "$AOS_REPO_ROOT/infra/livekit/" "$BACKUP_DIR/config/livekit/" 2>/dev/null || true
fi

cat > "$BACKUP_DIR/metadata.env" <<META
BACKUP_VERSION=1
CREATED_AT_UTC=$TIMESTAMP
HOSTNAME=$(hostname -f 2>/dev/null || hostname)
FRAPPE_SITE=$FRAPPE_SITE
AOS_GIT_COMMIT=$(git -C "$AOS_REPO_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)
AOS_GIT_BRANCH=$(git -C "$AOS_REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
INCLUDE_MINIO_DATA=$INCLUDE_MINIO_DATA
INCLUDE_QDRANT_DATA=$INCLUDE_QDRANT_DATA
INCLUDE_NOMINATIM_DATA=$INCLUDE_NOMINATIM_DATA
INCLUDE_MAP_ARTIFACTS=$INCLUDE_MAP_ARTIFACTS
META

log "Generating checksums"
(
  cd "$BACKUP_DIR"
  find . -type f ! -name SHA256SUMS -print0 | sort -z | xargs -0 sha256sum > SHA256SUMS
)

"$SCRIPT_DIR/verify-backup.sh" "$BACKUP_DIR"
date -u +%FT%TZ > "$BACKUP_DIR/VERIFIED_AT_UTC"

OFFSITE_BACKUP_MODE="${OFFSITE_BACKUP_MODE:-}"
OFFSITE_BACKUP_ENABLED="${OFFSITE_BACKUP_ENABLED:-false}"
if [[ -n "$REMOTE_COPY_COMMAND" || -n "$OFFSITE_BACKUP_MODE" || "${OFFSITE_BACKUP_ENABLED,,}" =~ ^(1|true|yes|on)$ ]]; then
  log "Copying backup to offsite storage"
  "$SCRIPT_DIR/offsite-copy.sh" "$BACKUP_DIR"
fi

log "Applying retention policy: ${BACKUP_RETENTION_DAYS} days"
find "$BACKUP_ROOT" -mindepth 1 -maxdepth 1 -type d -mtime "+$BACKUP_RETENTION_DAYS" -print -exec rm -rf {} +

trap - EXIT INT TERM
cleanup
log "Backup completed: $BACKUP_DIR"
