"""
Rate limit constants for Call endpoints.
"""

INITIATE_CALL_LIMIT_PER_MINUTE_PER_USER = 30
ACCEPT_CALL_LIMIT_PER_MINUTE_PER_USER = 60
REJECT_CALL_LIMIT_PER_MINUTE_PER_USER = 60
END_CALL_LIMIT_PER_MINUTE_PER_USER = 60
GET_TOKEN_LIMIT_PER_MINUTE_PER_USER = 120
LIST_CALLS_LIMIT_PER_MINUTE_PER_USER = 120